-- MySQL Script generated by MySQL Workbench
-- 02/16/15 18:21:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema omandb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema omandb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `omandb` DEFAULT CHARACTER SET latin1 ;
USE `omandb` ;

-- -----------------------------------------------------
-- Table `omandb`.`world`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`world` (
  `world_id` INT(11) NOT NULL AUTO_INCREMENT,
  `world_name` VARCHAR(50) NOT NULL,
  `world_description` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`world_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`downloads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`downloads` (
  `downloads_id` INT(11) NOT NULL,
  `world_id` INT(11) NULL DEFAULT NULL,
  `download_funstuff` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`downloads_id`),
  INDEX `world_id` (`world_id` ASC),
  CONSTRAINT `downloads_ibfk_1`
    FOREIGN KEY (`world_id`)
    REFERENCES `omandb`.`world` (`world_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`family` (
  `family_id` INT(11) NOT NULL AUTO_INCREMENT,
  `family_name` VARCHAR(50) NOT NULL,
  `family_description` VARCHAR(10000) NULL DEFAULT NULL,
  `world_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`family_id`),
  UNIQUE INDEX `FamilyName` (`family_name` ASC),
  INDEX `fk_world_id_idx` (`world_id` ASC),
  CONSTRAINT `fk_world_id`
    FOREIGN KEY (`world_id`)
    REFERENCES `omandb`.`world` (`world_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`subfamily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`subfamily` (
  `subfamily_id` INT(11) NOT NULL AUTO_INCREMENT,
  `family_id` INT(11) NOT NULL,
  `subfamily_name` VARCHAR(50) NOT NULL,
  `subfamily_description` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`subfamily_id`),
  INDEX `family_id` (`family_id` ASC),
  CONSTRAINT `subfamily_ibfk_1`
    FOREIGN KEY (`family_id`)
    REFERENCES `omandb`.`family` (`family_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`organism` (
  `organism_id` INT(11) NOT NULL AUTO_INCREMENT,
  `scientific_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `common_name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `local_name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `subfamily_id` INT(11) NULL DEFAULT NULL,
  `organism_description` VARCHAR(9000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `population` VARCHAR(50) NULL DEFAULT NULL,
  `indigenous` TINYINT(1) NULL DEFAULT NULL,
  `cultivated` TINYINT(1) NULL DEFAULT NULL,
  `endangered` TINYINT(1) NULL DEFAULT NULL,
  `medicinal` TINYINT(1) NULL DEFAULT NULL,
  `benefits` VARCHAR(2000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dangerous` VARCHAR(2000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `threats` VARCHAR(2000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `opportunities` VARCHAR(2000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `photo` MEDIUMBLOB NULL DEFAULT NULL,
  `links` VARCHAR(2000) NULL DEFAULT NULL,
  `food_name` VARCHAR(50) NOT NULL,
  `food_description` VARCHAR(10000) NOT NULL,
  `isvalidated` TINYINT(1) NOT NULL,
  `date_input` DATETIME NOT NULL,
  PRIMARY KEY (`organism_id`),
  UNIQUE INDEX `SCIENTIFICNAME` (`scientific_name` ASC),
  INDEX `subfamily_id` (`subfamily_id` ASC),
  CONSTRAINT `organism_ibfk_1`
    FOREIGN KEY (`subfamily_id`)
    REFERENCES `omandb`.`subfamily` (`subfamily_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`food` (
  `food_id` INT(11) NOT NULL AUTO_INCREMENT,
  `eaten_by_organism_id` INT(11) NULL DEFAULT NULL,
  `eating_organism_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`food_id`),
  INDEX `Eaten_Organism_ID` (`eaten_by_organism_id` ASC),
  INDEX `Eating_organism_ID` (`eating_organism_id` ASC),
  CONSTRAINT `Fk_LivingOrganismEaten_ID`
    FOREIGN KEY (`eaten_by_organism_id`)
    REFERENCES `omandb`.`organism` (`organism_id`),
  CONSTRAINT `Fk_LivingOrganismEatening_ID`
    FOREIGN KEY (`eating_organism_id`)
    REFERENCES `omandb`.`organism` (`organism_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`geolocation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`geolocation` (
  `geolocation_id` INT(11) NOT NULL AUTO_INCREMENT,
  `area_name` VARCHAR(50) NOT NULL,
  `area_description` VARCHAR(10000) NOT NULL,
  `latitude_height_1` VARCHAR(50) NULL DEFAULT NULL,
  `longitude_height_1` VARCHAR(50) NULL DEFAULT NULL,
  `latitude_width_1` VARCHAR(50) NULL DEFAULT NULL,
  `longitude_width_1` VARCHAR(50) NULL DEFAULT NULL,
  `latitude_height_2` VARCHAR(50) NULL DEFAULT NULL,
  `longitude_height_2` VARCHAR(50) NULL DEFAULT NULL,
  `latitude_width_2` VARCHAR(50) NULL DEFAULT NULL,
  `longitude_width_2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`geolocation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`geolocation_organisme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`geolocation_organisme` (
  `organism_id` INT(11) NOT NULL,
  `geolocation_id` INT(11) NOT NULL,
  INDEX `organism_id` (`organism_id` ASC),
  INDEX `geolocation_id` (`geolocation_id` ASC),
  CONSTRAINT `geolocation_organisme_ibfk_1`
    FOREIGN KEY (`organism_id`)
    REFERENCES `omandb`.`organism` (`organism_id`),
  CONSTRAINT `geolocation_organisme_ibfk_2`
    FOREIGN KEY (`geolocation_id`)
    REFERENCES `omandb`.`geolocation` (`geolocation_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`habitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`habitat` (
  `habitat_id` INT(11) NOT NULL AUTO_INCREMENT,
  `habitat_name` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(10000) NULL DEFAULT NULL,
  PRIMARY KEY (`habitat_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`habitat_organism`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`habitat_organism` (
  `habitat_id` INT(11) NULL DEFAULT NULL,
  `organism_id` INT(11) NULL DEFAULT NULL,
  INDEX `habitat_id` (`habitat_id` ASC),
  INDEX `organism_id` (`organism_id` ASC),
  CONSTRAINT `habitat_organism_ibfk_1`
    FOREIGN KEY (`habitat_id`)
    REFERENCES `omandb`.`habitat` (`habitat_id`),
  CONSTRAINT `habitat_organism_ibfk_2`
    FOREIGN KEY (`organism_id`)
    REFERENCES `omandb`.`organism` (`organism_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`season` (
  `season_id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `description` VARCHAR(10000) NOT NULL,
  PRIMARY KEY (`season_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`organism_season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`organism_season` (
  `organism_id` INT(11) NULL DEFAULT NULL,
  `season_id` INT(11) NULL DEFAULT NULL,
  INDEX `living_organism_id` (`organism_id` ASC),
  INDEX `season_id` (`season_id` ASC),
  CONSTRAINT `organism_season_ibfk_1`
    FOREIGN KEY (`organism_id`)
    REFERENCES `omandb`.`organism` (`organism_id`),
  CONSTRAINT `organism_season_ibfk_2`
    FOREIGN KEY (`season_id`)
    REFERENCES `omandb`.`season` (`season_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`post` (
  `post_id` INT(11) NOT NULL AUTO_INCREMENT,
  `organism_id` INT(11) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `post_description` VARCHAR(10000) NULL DEFAULT NULL,
  `photo_post` MEDIUMBLOB NULL DEFAULT NULL,
  `longitude` VARCHAR(50) NULL DEFAULT NULL,
  `latitude` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `LivingOrganismID` (`organism_id` ASC),
  CONSTRAINT `FK_Livingorganisms_ID`
    FOREIGN KEY (`organism_id`)
    REFERENCES `omandb`.`organism` (`organism_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`subscribed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`subscribed` (
  `subscribed_id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`subscribed_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `omandb`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `omandb`.`user_account` (
  `username` VARCHAR(50) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `isadmin` TINYINT(1) NOT NULL,
  `phone` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `email` (`email` ASC),
  PRIMARY KEY (`username`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
