package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1



/**
 * Downloads generated by hbm2java
 */
public class Downloads  implements java.io.Serializable {


     private int downloadsId;
     private Worlds worlds;
     private String downloadFunstuff;

    public Downloads() {
    }

	
    public Downloads(int downloadsId) {
        this.downloadsId = downloadsId;
    }
    public Downloads(int downloadsId, Worlds worlds, String downloadFunstuff) {
       this.downloadsId = downloadsId;
       this.worlds = worlds;
       this.downloadFunstuff = downloadFunstuff;
    }
   
    public int getDownloadsId() {
        return this.downloadsId;
    }
    
    public void setDownloadsId(int downloadsId) {
        this.downloadsId = downloadsId;
    }
    public Worlds getWorlds() {
        return this.worlds;
    }
    
    public void setWorlds(Worlds worlds) {
        this.worlds = worlds;
    }
    public String getDownloadFunstuff() {
        return this.downloadFunstuff;
    }
    
    public void setDownloadFunstuff(String downloadFunstuff) {
        this.downloadFunstuff = downloadFunstuff;
    }




}


