package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Family generated by hbm2java
 */
public class Family  implements java.io.Serializable {


     private Integer famillyId;
     private String famillyName;
     private String description;
     private Set subfamillies = new HashSet(0);

    public Family() {
    }

	
    public Family(String famillyName) {
        this.famillyName = famillyName;
    }
    public Family(String famillyName, String description, Set subfamillies) {
       this.famillyName = famillyName;
       this.description = description;
       this.subfamillies = subfamillies;
    }
   
    public Integer getFamillyId() {
        return this.famillyId;
    }
    
    public void setFamillyId(Integer famillyId) {
        this.famillyId = famillyId;
    }
    public String getFamillyName() {
        return this.famillyName;
    }
    
    public void setFamillyName(String famillyName) {
        this.famillyName = famillyName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getSubfamillies() {
        return this.subfamillies;
    }
    
    public void setSubfamillies(Set subfamillies) {
        this.subfamillies = subfamillies;
    }




}


