package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1



/**
 * Food generated by hbm2java
 */
public class Food  implements java.io.Serializable {


     private Integer foodId;
     private Organism organismByEatenByOrganismeId;
     private Organism organismByEatingOrganismeId;

    public Food() {
    }

    public Food(Organism organismByEatenByOrganismeId, Organism organismByEatingOrganismeId) {
       this.organismByEatenByOrganismeId = organismByEatenByOrganismeId;
       this.organismByEatingOrganismeId = organismByEatingOrganismeId;
    }
   
    public Integer getFoodId() {
        return this.foodId;
    }
    
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }
    public Organism getOrganismByEatenByOrganismeId() {
        return this.organismByEatenByOrganismeId;
    }
    
    public void setOrganismByEatenByOrganismeId(Organism organismByEatenByOrganismeId) {
        this.organismByEatenByOrganismeId = organismByEatenByOrganismeId;
    }
    public Organism getOrganismByEatingOrganismeId() {
        return this.organismByEatingOrganismeId;
    }
    
    public void setOrganismByEatingOrganismeId(Organism organismByEatingOrganismeId) {
        this.organismByEatingOrganismeId = organismByEatingOrganismeId;
    }




}


