package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1



/**
 * Geolocation generated by hbm2java
 */
public class Geolocation  implements java.io.Serializable {


     private Integer geolocationId;
     private Organism organism;
     private String areaName;
     private String areaDescription;
     private String latitudeHeight1;
     private String longitudeHeigth1;
     private String latitudeWidth1;
     private String longitudeWidth1;
     private String latitudeHeigth2;
     private String longitudeHeight2;
     private String latitudeWidth2;
     private String longitudeWidth2;

    public Geolocation() {
    }

	
    public Geolocation(Organism organism, String areaName, String areaDescription) {
        this.organism = organism;
        this.areaName = areaName;
        this.areaDescription = areaDescription;
    }
    public Geolocation(Organism organism, String areaName, String areaDescription, String latitudeHeight1, String longitudeHeigth1, String latitudeWidth1, String longitudeWidth1, String latitudeHeigth2, String longitudeHeight2, String latitudeWidth2, String longitudeWidth2) {
       this.organism = organism;
       this.areaName = areaName;
       this.areaDescription = areaDescription;
       this.latitudeHeight1 = latitudeHeight1;
       this.longitudeHeigth1 = longitudeHeigth1;
       this.latitudeWidth1 = latitudeWidth1;
       this.longitudeWidth1 = longitudeWidth1;
       this.latitudeHeigth2 = latitudeHeigth2;
       this.longitudeHeight2 = longitudeHeight2;
       this.latitudeWidth2 = latitudeWidth2;
       this.longitudeWidth2 = longitudeWidth2;
    }
   
    public Integer getGeolocationId() {
        return this.geolocationId;
    }
    
    public void setGeolocationId(Integer geolocationId) {
        this.geolocationId = geolocationId;
    }
    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }
    public String getAreaDescription() {
        return this.areaDescription;
    }
    
    public void setAreaDescription(String areaDescription) {
        this.areaDescription = areaDescription;
    }
    public String getLatitudeHeight1() {
        return this.latitudeHeight1;
    }
    
    public void setLatitudeHeight1(String latitudeHeight1) {
        this.latitudeHeight1 = latitudeHeight1;
    }
    public String getLongitudeHeigth1() {
        return this.longitudeHeigth1;
    }
    
    public void setLongitudeHeigth1(String longitudeHeigth1) {
        this.longitudeHeigth1 = longitudeHeigth1;
    }
    public String getLatitudeWidth1() {
        return this.latitudeWidth1;
    }
    
    public void setLatitudeWidth1(String latitudeWidth1) {
        this.latitudeWidth1 = latitudeWidth1;
    }
    public String getLongitudeWidth1() {
        return this.longitudeWidth1;
    }
    
    public void setLongitudeWidth1(String longitudeWidth1) {
        this.longitudeWidth1 = longitudeWidth1;
    }
    public String getLatitudeHeigth2() {
        return this.latitudeHeigth2;
    }
    
    public void setLatitudeHeigth2(String latitudeHeigth2) {
        this.latitudeHeigth2 = latitudeHeigth2;
    }
    public String getLongitudeHeight2() {
        return this.longitudeHeight2;
    }
    
    public void setLongitudeHeight2(String longitudeHeight2) {
        this.longitudeHeight2 = longitudeHeight2;
    }
    public String getLatitudeWidth2() {
        return this.latitudeWidth2;
    }
    
    public void setLatitudeWidth2(String latitudeWidth2) {
        this.latitudeWidth2 = latitudeWidth2;
    }
    public String getLongitudeWidth2() {
        return this.longitudeWidth2;
    }
    
    public void setLongitudeWidth2(String longitudeWidth2) {
        this.longitudeWidth2 = longitudeWidth2;
    }




}


