package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1



/**
 * HabitatOrganisme generated by hbm2java
 */
public class HabitatOrganisme  implements java.io.Serializable {


     private Integer habitatOrganismeId;
     private Habitat habitat;
     private Organism organism;

    public HabitatOrganisme() {
    }

    public HabitatOrganisme(Habitat habitat, Organism organism) {
       this.habitat = habitat;
       this.organism = organism;
    }
   
    public Integer getHabitatOrganismeId() {
        return this.habitatOrganismeId;
    }
    
    public void setHabitatOrganismeId(Integer habitatOrganismeId) {
        this.habitatOrganismeId = habitatOrganismeId;
    }
    public Habitat getHabitat() {
        return this.habitat;
    }
    
    public void setHabitat(Habitat habitat) {
        this.habitat = habitat;
    }
    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }




}


