package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OrganismSeason generated by hbm2java
 */
public class OrganismSeason  implements java.io.Serializable {


     private Integer organismSeasonId;
     private Organism organism;
     private Season season;
     private Set organisms = new HashSet(0);

    public OrganismSeason() {
    }

    public OrganismSeason(Organism organism, Season season, Set organisms) {
       this.organism = organism;
       this.season = season;
       this.organisms = organisms;
    }
   
    public Integer getOrganismSeasonId() {
        return this.organismSeasonId;
    }
    
    public void setOrganismSeasonId(Integer organismSeasonId) {
        this.organismSeasonId = organismSeasonId;
    }
    public Organism getOrganism() {
        return this.organism;
    }
    
    public void setOrganism(Organism organism) {
        this.organism = organism;
    }
    public Season getSeason() {
        return this.season;
    }
    
    public void setSeason(Season season) {
        this.season = season;
    }
    public Set getOrganisms() {
        return this.organisms;
    }
    
    public void setOrganisms(Set organisms) {
        this.organisms = organisms;
    }




}


