package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organism generated by hbm2java
 */
public class Organism  implements java.io.Serializable {


     private Integer organismId;
     private OrganismSeason organismSeason;
     private Subfamilly subfamilly;
     private Worlds worlds;
     private String scientificName;
     private String commmonName;
     private String localName;
     private String description;
     private String population;
     private Boolean indigenous;
     private Boolean cultivated;
     private Boolean endangered;
     private Boolean medicinal;
     private String benefits;
     private String dangerous;
     private String threats;
     private String opportunities;
     private byte[] photo;
     private String links;
     private byte[] qr;
     private String foodName;
     private String foodDescription;
     private Set foodsForEatenByOrganismeId = new HashSet(0);
     private Set posts = new HashSet(0);
     private Set organismSeasons = new HashSet(0);
     private Set foodsForEatingOrganismeId = new HashSet(0);
     private Set habitatOrganismes = new HashSet(0);
     private Set geolocations = new HashSet(0);

    public Organism() {
    }

	
    public Organism(String scientificName, String foodName, String foodDescription) {
        this.scientificName = scientificName;
        this.foodName = foodName;
        this.foodDescription = foodDescription;
    }
    public Organism(OrganismSeason organismSeason, Subfamilly subfamilly, Worlds worlds, String scientificName, String commmonName, String localName, String description, String population, Boolean indigenous, Boolean cultivated, Boolean endangered, Boolean medicinal, String benefits, String dangerous, String threats, String opportunities, byte[] photo, String links, byte[] qr, String foodName, String foodDescription, Set foodsForEatenByOrganismeId, Set posts, Set organismSeasons, Set foodsForEatingOrganismeId, Set habitatOrganismes, Set geolocations) {
       this.organismSeason = organismSeason;
       this.subfamilly = subfamilly;
       this.worlds = worlds;
       this.scientificName = scientificName;
       this.commmonName = commmonName;
       this.localName = localName;
       this.description = description;
       this.population = population;
       this.indigenous = indigenous;
       this.cultivated = cultivated;
       this.endangered = endangered;
       this.medicinal = medicinal;
       this.benefits = benefits;
       this.dangerous = dangerous;
       this.threats = threats;
       this.opportunities = opportunities;
       this.photo = photo;
       this.links = links;
       this.qr = qr;
       this.foodName = foodName;
       this.foodDescription = foodDescription;
       this.foodsForEatenByOrganismeId = foodsForEatenByOrganismeId;
       this.posts = posts;
       this.organismSeasons = organismSeasons;
       this.foodsForEatingOrganismeId = foodsForEatingOrganismeId;
       this.habitatOrganismes = habitatOrganismes;
       this.geolocations = geolocations;
    }
   
    public Integer getOrganismId() {
        return this.organismId;
    }
    
    public void setOrganismId(Integer organismId) {
        this.organismId = organismId;
    }
    public OrganismSeason getOrganismSeason() {
        return this.organismSeason;
    }
    
    public void setOrganismSeason(OrganismSeason organismSeason) {
        this.organismSeason = organismSeason;
    }
    public Subfamilly getSubfamilly() {
        return this.subfamilly;
    }
    
    public void setSubfamilly(Subfamilly subfamilly) {
        this.subfamilly = subfamilly;
    }
    public Worlds getWorlds() {
        return this.worlds;
    }
    
    public void setWorlds(Worlds worlds) {
        this.worlds = worlds;
    }
    public String getScientificName() {
        return this.scientificName;
    }
    
    public void setScientificName(String scientificName) {
        this.scientificName = scientificName;
    }
    public String getCommmonName() {
        return this.commmonName;
    }
    
    public void setCommmonName(String commmonName) {
        this.commmonName = commmonName;
    }
    public String getLocalName() {
        return this.localName;
    }
    
    public void setLocalName(String localName) {
        this.localName = localName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPopulation() {
        return this.population;
    }
    
    public void setPopulation(String population) {
        this.population = population;
    }
    public Boolean getIndigenous() {
        return this.indigenous;
    }
    
    public void setIndigenous(Boolean indigenous) {
        this.indigenous = indigenous;
    }
    public Boolean getCultivated() {
        return this.cultivated;
    }
    
    public void setCultivated(Boolean cultivated) {
        this.cultivated = cultivated;
    }
    public Boolean getEndangered() {
        return this.endangered;
    }
    
    public void setEndangered(Boolean endangered) {
        this.endangered = endangered;
    }
    public Boolean getMedicinal() {
        return this.medicinal;
    }
    
    public void setMedicinal(Boolean medicinal) {
        this.medicinal = medicinal;
    }
    public String getBenefits() {
        return this.benefits;
    }
    
    public void setBenefits(String benefits) {
        this.benefits = benefits;
    }
    public String getDangerous() {
        return this.dangerous;
    }
    
    public void setDangerous(String dangerous) {
        this.dangerous = dangerous;
    }
    public String getThreats() {
        return this.threats;
    }
    
    public void setThreats(String threats) {
        this.threats = threats;
    }
    public String getOpportunities() {
        return this.opportunities;
    }
    
    public void setOpportunities(String opportunities) {
        this.opportunities = opportunities;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public String getLinks() {
        return this.links;
    }
    
    public void setLinks(String links) {
        this.links = links;
    }
    public byte[] getQr() {
        return this.qr;
    }
    
    public void setQr(byte[] qr) {
        this.qr = qr;
    }
    public String getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }
    public String getFoodDescription() {
        return this.foodDescription;
    }
    
    public void setFoodDescription(String foodDescription) {
        this.foodDescription = foodDescription;
    }
    public Set getFoodsForEatenByOrganismeId() {
        return this.foodsForEatenByOrganismeId;
    }
    
    public void setFoodsForEatenByOrganismeId(Set foodsForEatenByOrganismeId) {
        this.foodsForEatenByOrganismeId = foodsForEatenByOrganismeId;
    }
    public Set getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set posts) {
        this.posts = posts;
    }
    public Set getOrganismSeasons() {
        return this.organismSeasons;
    }
    
    public void setOrganismSeasons(Set organismSeasons) {
        this.organismSeasons = organismSeasons;
    }
    public Set getFoodsForEatingOrganismeId() {
        return this.foodsForEatingOrganismeId;
    }
    
    public void setFoodsForEatingOrganismeId(Set foodsForEatingOrganismeId) {
        this.foodsForEatingOrganismeId = foodsForEatingOrganismeId;
    }
    public Set getHabitatOrganismes() {
        return this.habitatOrganismes;
    }
    
    public void setHabitatOrganismes(Set habitatOrganismes) {
        this.habitatOrganismes = habitatOrganismes;
    }
    public Set getGeolocations() {
        return this.geolocations;
    }
    
    public void setGeolocations(Set geolocations) {
        this.geolocations = geolocations;
    }




}


