package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Season generated by hbm2java
 */
public class Season  implements java.io.Serializable {


     private Integer seasonId;
     private String name;
     private String description;
     private Set organismSeasons = new HashSet(0);

    public Season() {
    }

	
    public Season(String name, String description) {
        this.name = name;
        this.description = description;
    }
    public Season(String name, String description, Set organismSeasons) {
       this.name = name;
       this.description = description;
       this.organismSeasons = organismSeasons;
    }
   
    public Integer getSeasonId() {
        return this.seasonId;
    }
    
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrganismSeasons() {
        return this.organismSeasons;
    }
    
    public void setOrganismSeasons(Set organismSeasons) {
        this.organismSeasons = organismSeasons;
    }




}


