package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subfamilly generated by hbm2java
 */
public class Subfamilly  implements java.io.Serializable {


     private Integer subfamilyId;
     private Family family;
     private String subfamillyName;
     private String description;
     private Set organisms = new HashSet(0);

    public Subfamilly() {
    }

	
    public Subfamilly(Family family, String subfamillyName, String description) {
        this.family = family;
        this.subfamillyName = subfamillyName;
        this.description = description;
    }
    public Subfamilly(Family family, String subfamillyName, String description, Set organisms) {
       this.family = family;
       this.subfamillyName = subfamillyName;
       this.description = description;
       this.organisms = organisms;
    }
   
    public Integer getSubfamilyId() {
        return this.subfamilyId;
    }
    
    public void setSubfamilyId(Integer subfamilyId) {
        this.subfamilyId = subfamilyId;
    }
    public Family getFamily() {
        return this.family;
    }
    
    public void setFamily(Family family) {
        this.family = family;
    }
    public String getSubfamillyName() {
        return this.subfamillyName;
    }
    
    public void setSubfamillyName(String subfamillyName) {
        this.subfamillyName = subfamillyName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrganisms() {
        return this.organisms;
    }
    
    public void setOrganisms(Set organisms) {
        this.organisms = organisms;
    }




}


