package dal;
// Generated 13-feb-2015 0:06:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Worlds generated by hbm2java
 */
public class Worlds  implements java.io.Serializable {


     private Integer worldId;
     private String name;
     private String description;
     private Set organisms = new HashSet(0);
     private Set downloadses = new HashSet(0);

    public Worlds() {
    }

    public Worlds(String name, String description, Set organisms, Set downloadses) {
       this.name = name;
       this.description = description;
       this.organisms = organisms;
       this.downloadses = downloadses;
    }
   
    public Integer getWorldId() {
        return this.worldId;
    }
    
    public void setWorldId(Integer worldId) {
        this.worldId = worldId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getOrganisms() {
        return this.organisms;
    }
    
    public void setOrganisms(Set organisms) {
        this.organisms = organisms;
    }
    public Set getDownloadses() {
        return this.downloadses;
    }
    
    public void setDownloadses(Set downloadses) {
        this.downloadses = downloadses;
    }




}


